name: Deploy to Vercel

jobs:
  deploy:
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
